let
    ExcelFilePath = "C:\Users\ksaik\OneDrive\Desktop\MSCriptAutomation\MSCriptAutomation\combined_datasets.xlsx",
    SchemaPath    = "C:\Users\ksaik\OneDrive\Desktop\MSCriptAutomation\MSCriptAutomation\excel_schema.json",
    FlowJsonPath  = "C:\Users\ksaik\OneDrive\Desktop\MSCriptAutomation\MSCriptAutomation\New_Dashboard_Parameter_Updated.json",

    // Load JSON in M
    Schema = Json.Document(File.Contents(SchemaPath)),
    Flow   = Json.Document(File.Contents(FlowJsonPath)),

    Source = Excel.Workbook(File.Contents(ExcelFilePath), null, true),
    GetSheet = (tableName as text) as table =>
        let
            wb = Source,
            sht = try wb{[Item=tableName,Kind="Sheet"]}[Data] otherwise #table({}, {}),
            promoted = Table.PromoteHeaders(sht, [PromoteAllScalars=true])
        in promoted,

    // Load tables dynamically
    Clinic_Stats_Migrated_Data = GetSheet("Clinic Stats_Migrated Data"),
    Clinical_Unit_Costs_Migrated_Da = GetSheet("Clinical Unit Costs_Migrated Da"),

    ChangedType_Clinic_Stats_Migrated_Data = Table.TransformColumnTypes(Clinic_Stats_Migrated_Data, {{"Admit Source", type any}, {"Admit Type", type any}, {"Appt Start Time", type any}, {"Check In Time", type any}, {"Clinical Unit", type any}, {"Cohort", type any}, {"Diagnosis Primary", type any}, {"Discharge Datetime", type any}, {"Encounter Number", type any}, {"Encounter Status", type any}, {"Gender", type any}, {"Hospital LOS", type any}, {"Hospital Room Number", type any}, {"MRN Number", type any}, {"Patient Address Zipcode", type any}, {"Procedure (Icd9) Primary", type any}, {"Religion", type any}, {"Strategic Planning Line Code", type any}, {"Age", type any}, {"Care Score", type any}, {"Logistics Score", type any}, {"LOS", type any}, {"Number of Patients", type any}, {"Number of Records", type any}, {"Wait Time Days", type any}, {"Wait Time KPI", type any}, {"Wait Time Min", type any}}),
    Filtered_Clinic_Stats_Migrated_Data = Table.SelectRows(ChangedType_Clinic_Stats_Migrated_Data, each (if Table.HasColumns(ChangedType_Clinic_Stats_Migrated_Data, "Admit Source") then Record.Field(_, "Admit Source") <> null else true) and (if Table.HasColumns(ChangedType_Clinic_Stats_Migrated_Data, "Admit Type") then Record.Field(_, "Admit Type") <> null else true) and (if Table.HasColumns(ChangedType_Clinic_Stats_Migrated_Data, "Appt Start Time") then Record.Field(_, "Appt Start Time") <> null else true) and (if Table.HasColumns(ChangedType_Clinic_Stats_Migrated_Data, "Check In Time") then Record.Field(_, "Check In Time") <> null else true) and (if Table.HasColumns(ChangedType_Clinic_Stats_Migrated_Data, "Clinical Unit") then Record.Field(_, "Clinical Unit") <> null else true) and (if Table.HasColumns(ChangedType_Clinic_Stats_Migrated_Data, "Cohort") then Record.Field(_, "Cohort") <> null else true) and (if Table.HasColumns(ChangedType_Clinic_Stats_Migrated_Data, "Diagnosis Primary") then Record.Field(_, "Diagnosis Primary") <> null else true) and (if Table.HasColumns(ChangedType_Clinic_Stats_Migrated_Data, "Discharge Datetime") then Record.Field(_, "Discharge Datetime") <> null else true) and (if Table.HasColumns(ChangedType_Clinic_Stats_Migrated_Data, "Encounter Number") then Record.Field(_, "Encounter Number") <> null else true) and (if Table.HasColumns(ChangedType_Clinic_Stats_Migrated_Data, "Encounter Status") then Record.Field(_, "Encounter Status") <> null else true) and (if Table.HasColumns(ChangedType_Clinic_Stats_Migrated_Data, "Gender") then Record.Field(_, "Gender") <> null else true) and (if Table.HasColumns(ChangedType_Clinic_Stats_Migrated_Data, "Hospital LOS") then Record.Field(_, "Hospital LOS") <> null else true) and (if Table.HasColumns(ChangedType_Clinic_Stats_Migrated_Data, "Hospital Room Number") then Record.Field(_, "Hospital Room Number") <> null else true) and (if Table.HasColumns(ChangedType_Clinic_Stats_Migrated_Data, "MRN Number") then Record.Field(_, "MRN Number") <> null else true) and (if Table.HasColumns(ChangedType_Clinic_Stats_Migrated_Data, "Patient Address Zipcode") then Record.Field(_, "Patient Address Zipcode") <> null else true) and (if Table.HasColumns(ChangedType_Clinic_Stats_Migrated_Data, "Procedure (Icd9) Primary") then Record.Field(_, "Procedure (Icd9) Primary") <> null else true) and (if Table.HasColumns(ChangedType_Clinic_Stats_Migrated_Data, "Religion") then Record.Field(_, "Religion") <> null else true) and (if Table.HasColumns(ChangedType_Clinic_Stats_Migrated_Data, "Strategic Planning Line Code") then Record.Field(_, "Strategic Planning Line Code") <> null else true) and (if Table.HasColumns(ChangedType_Clinic_Stats_Migrated_Data, "Age") then Record.Field(_, "Age") <> null else true) and (if Table.HasColumns(ChangedType_Clinic_Stats_Migrated_Data, "Care Score") then Record.Field(_, "Care Score") <> null else true) and (if Table.HasColumns(ChangedType_Clinic_Stats_Migrated_Data, "Logistics Score") then Record.Field(_, "Logistics Score") <> null else true) and (if Table.HasColumns(ChangedType_Clinic_Stats_Migrated_Data, "LOS") then Record.Field(_, "LOS") <> null else true) and (if Table.HasColumns(ChangedType_Clinic_Stats_Migrated_Data, "Number of Patients") then Record.Field(_, "Number of Patients") <> null else true) and (if Table.HasColumns(ChangedType_Clinic_Stats_Migrated_Data, "Number of Records") then Record.Field(_, "Number of Records") <> null else true) and (if Table.HasColumns(ChangedType_Clinic_Stats_Migrated_Data, "Wait Time Days") then Record.Field(_, "Wait Time Days") <> null else true) and (if Table.HasColumns(ChangedType_Clinic_Stats_Migrated_Data, "Wait Time KPI") then Record.Field(_, "Wait Time KPI") <> null else true) and (if Table.HasColumns(ChangedType_Clinic_Stats_Migrated_Data, "Wait Time Min") then Record.Field(_, "Wait Time Min") <> null else true)),
    ChangedType_Clinical_Unit_Costs_Migrated_Da = Table.TransformColumnTypes(Clinical_Unit_Costs_Migrated_Da, {{"Clinical Unit", type any}, {"Episode Start Datetime", type any}, {"MRN Number", type any}, {"Patient Address Zipcode", type any}, {"Daily Cost", type any}, {"Number of Records", type any}}),
    Filtered_Clinical_Unit_Costs_Migrated_Da = Table.SelectRows(ChangedType_Clinical_Unit_Costs_Migrated_Da, each (if Table.HasColumns(ChangedType_Clinical_Unit_Costs_Migrated_Da, "Clinical Unit") then Record.Field(_, "Clinical Unit") <> null else true) and (if Table.HasColumns(ChangedType_Clinical_Unit_Costs_Migrated_Da, "Episode Start Datetime") then Record.Field(_, "Episode Start Datetime") <> null else true) and (if Table.HasColumns(ChangedType_Clinical_Unit_Costs_Migrated_Da, "MRN Number") then Record.Field(_, "MRN Number") <> null else true) and (if Table.HasColumns(ChangedType_Clinical_Unit_Costs_Migrated_Da, "Patient Address Zipcode") then Record.Field(_, "Patient Address Zipcode") <> null else true) and (if Table.HasColumns(ChangedType_Clinical_Unit_Costs_Migrated_Da, "Daily Cost") then Record.Field(_, "Daily Cost") <> null else true) and (if Table.HasColumns(ChangedType_Clinical_Unit_Costs_Migrated_Da, "Number of Records") then Record.Field(_, "Number of Records") <> null else true)),

    // Apply join steps from flow

    FinalResult = Table.Combine({Filtered_Clinic_Stats_Migrated_Data, Filtered_Clinical_Unit_Costs_Migrated_Da})
in
    FinalResult